services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass
      POSTGRES_DB: shopdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  metabase:
    image: docker.io/metabase/metabase:latest
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  pgdata:
